### ISSUE TITLE
can the ss3 exe be named something other than ss.exe or ss when running MCMC?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ss3-source-code#319]
This issue is now resolved on Dec 21, 2023 by adding a command line argument invoked by the word "modelname".
For example:
```
ss3.exe -nohess -stopph 3 modelname ss4you
produces output like:
ss4you.par
```
The default value for modelname is "ss3" so this feature is only used if user wants a different name.

Note that if the user already has a par file, it may be named ss.par or ss3.par.  It will need to be renamed if modelname does not match the name of the existing par file.

Original inquiry:
I think this question came up at some point. @kellijohnson-NOAA , perhaps you know that answer to this? Can you use e.g., ss_win.exe or ss_lin  instead as the name for the stock synthesis executable when running MCMC?

**Comment by kellijohnson-NOAA** [comment]
You have a **GREAT** memory @k-doering-NOAA. I did mention this a while ago and I cannot remember what version of SS3 I was using at the time or the name of the file that it said it was missing. But, I just tested it with the current version and everything appears to be working fine even if I name the executable something other than ss.exe.

**Comment by kellijohnson-NOAA** [comment]
Reopening this issue because I finally remembered what was going haywire. When you run Stock Synthesis in mcmc mode you can do so with the executable being named anything you want. But, when you go to do -mceval it thinks that the `.psv` should ALWAYS be named `ss.psv` regardless of what the executable is named. @Rick-Methot-NOAA I think this is an ADMB thing not a SS3 thing, correct? Should I work with @johnoel to see what is going wrong here?

**Comment by Rick-Methot-NOAA** [comment]
Kelli,
the "ss" is coded near top of ss_param.tpl.
I can change that to ss3

**Comment by kellijohnson-NOAA** [comment]
Is there anyway to create it dynamically from the name of the executable rather than have it hard coded? Because as an example, I am currently using an executable called `ss3_2024.exe`, which then creates `ss3_2024.psv` but when I run mceval it is expecting `ss.psv`. So, even if you change the code in ss_param.tpl from ss.psv to ss3.psv I still have to write/do something to change `ss3_2024.psv` to the file name hard coded in ss_param.tpl.

**Comment by Rick-Methot-NOAA** [comment]
I do not think that is possible.  I did not anticipate a workflow as you describe.  I expected users to put ss3.exe in a folder called ss3_2024, or something like that.

**Comment by kellijohnson-NOAA** [comment]
Fair enough. Should, I start a new issue about changing the name of the ADMB files from ss to ss3, for example ss.psv and ss.par to ss3.psv and ss3.par. As it aligns with our current naming scheme but could break a lot of downstream code.

**Comment by Rick-Methot-NOAA** [comment]
Please do create the issue.  I have an idea about how the name could be read from the command line.
BTW, the current bootstrap function was broken and now fixed.  Look for 3.30.22.1 in early Jan

**Comment by e-perl-NOAA** [comment]
To add another case to what Kelli is saying, the exe names in the releases are currently ss_linux, ss_osx, ss_win.exe. Of course we can change these to be ss3_linux, ss3_osx, and ss3_win.exe but of course we still need to have the OS attached to the name of the exe. I could see people downloading the exe and using the default exe name such as `ss_win` or `ss3_win` - mceval might still be expecting `ss.psv` or `ss3.psv` but it should be `ss_win.psv` or `ss3_win.psv`.

**Comment by iantaylor-NOAA** [comment]
If we could package the assets for the release in some way that made it easy to differentiate the files for each operating system, then I it would be beneficial to change all the exe names to "ss3". In addition to the mceval issue, it would make our scripts simpler and require less work for folks running `r4ss::run()`.
If we put each asset into a zip file, the zip names could be OS-specific, but maybe that would have other unintended consequences. I think unzipping could be added to `r4ss::get_ss3_exe()` easily enough.

Also, is the error message associated with missing the ss.psv informative? If not, we could probably add a message that tells you to rename the .psv file.

**Comment by Rick-Methot-NOAA** [comment]
We already read and process command line arguments before reading starter.ss.  This occurs in readstarter.tpl
The assignment of the internal naming occurs in global.tpl.
So, I think it feasible to create a new command line input that would allow user to customize the internal name (default would be "ss3").  Perhaps would need to move the command line reads from readstarter to global.

**Comment by Rick-Methot-NOAA** [comment]
This was way too easy.  Will get a PR up for review soon.
 ss3_win.exe -nohess -stopph 3  modelname ss4you
will produce:
ss4you.par
ss4you.rep
etc.
hope it works for mcmc too.
