### ISSUE TITLE
Epic: Data weighting improvement

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ss3-source-code#332]
[Link to Issues](https://github.com/nmfs-stock-synthesis/stock-synthesis/labels/Epic%3A%20Data%20weighting%20improvement)

**Comment by k-doering-NOAA** [comment]
Note that Eli Holmes introduced the concept of "Epics" in the NWFSC summer github intro - basically an epic is a group of issues that are part of a bigger idea. I created Labels with Epic: for our issues in Stock Synthesis to see if it helps organized our ideas of "groups of issues" we had already been thinking about.

I also created a project board for the epics to help us monitor progress: https://github.com/orgs/nmfs-stock-synthesis/projects/8

Just trying this out, so feel free to provide any feedback about how this is working or not.

**Comment by Rick-Methot-NOAA** [comment]
seems a good innovation.  Something I had been trying to do with labels.

**Comment by k-doering-NOAA** [comment]
Yes, absolutely! I thought this concept basically captured what we already wanted to do, but didn't have a name for!

Some background, this is an idea from agile project management: https://www.atlassian.com/agile/project-management/epics
