### ISSUE TITLE
[Refactor]: combine workflows repo with stock-synthesis?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#416]
### Refactor request

@k-doering-NOAA and I were discussing how to keep the github actions working well with the least effort and concluded that it would be a good idea to move all the files from the `workflows` repo into the `stock-synthesis` repo. 

In the time since the `workflows` repo was first created, github actions have evolved and we have learned a lot and also discovered some of the challenges of having them in a separate place, such as the need to create a separate branch of `stock-synthesis` to test any branch in `workflows` when changing the github actions, rather than a single branch of a combined repository. 

Some of the files in the `workflows` repo are used by `doc`, rather than `stock-synthesis` and those could either be moved into the `doc` repo directly or we could just update which repo is referenced in lines like 
```
uses: nmfs-stock-synthesis/workflows/.github/workflows/build-ss3-manual-html.yml@main
```

I think the primary drawback of this approach is that changes to the github actions will now generate notifications for the watchers of `stock-synthesis` who are more numerous than the few watchers of `workflows`. However, now that these github actions are working well there are many fewer notifications than there were when they were first getting set up.

I'm happy to do the refactoring, perhaps with help with @k-doering-NOAA if needed, but want to post this as an issue to see if anyone has a problem with the proposed change or suggestions on whether to put all the files into `stock-synthesis` or distribute them to the package that uses them (I think `doc` may be the only other one).

### Expected behavior

Fewer moving parts to maintain and keep track of.

### Progress on Issue
|workflows|to|complete|
|---|---|---|
build-ss3-manual-html.yml | doc | :x:; PR in review |
build-ss3-manual-pdf.yml | doc | :x:; PR in review |
build-ss3-warnings.yml | stock-synthesis | ✔️ |
build-ss3.yml | stock-synthesis | ✔️ |
check-ss3-models-run.yml | user-examples | ✔️ |
deploy-ss3-docs.yml | doc | :x:; PR in review |
r4ss-extra-tests.yml | r4ss | ✔️ |
run-ss3-mcmc.yml | stock-synthesis | ✔️ |
run-ss3-no-est.yml | stock-synthesis | ✔️ |
run-ss3-with-est.yml | stock-synthesis | ✔️ |
test-r4ss-with-ss3.yml | stock-synthesis | ✔️ |
update-ss3-version.yml | ss3sim | :x:; PR in review |
update-ss3-version.yml | ssmse | :x: |

- [x] Migrate or close issues from workflows repo.

**Comment by Rick-Methot-NOAA** [comment]
does this mean that a change to the workflow will trigger a run of all the test models?

**Comment by iantaylor-NOAA** [comment]
Good question. This case is a bit tricky because if we break the test via changes to the workflow files, rather than a change to the model, we probably want to figure that out quickly. But there are also probably trivial changes that we wouldn't want to trigger the tests. 

I think that we can set it up to ignore changes to the workflow files in the .github folder and then make sure to manually run the tests if we make a change there that we want to confirm as not breaking anything. @k-doering-NOAA, could you confirm that?

**Comment by kellijohnson-NOAA** [comment]
You can very easily set it up such that the test models are only ran when there are changes to the tpl files. You can just use a regex expression to tell it what kind of files you want to test if there are changes.

**Comment by k-doering-NOAA** [comment]
agree with Kelli, It actually might already be set up like this, actually, so we could just copy over build triggers

**Comment by iantaylor-NOAA** [comment]
Thanks @kellijohnson-NOAA and @k-doering-NOAA.

You inspired me to look at the files and I see now that it looks like the current workflows build the executable only when there's a change to the .tpl or .sh files: https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/.github/workflows/call-build-ss3.yml#L5-L7

Then models only get run when there are either changes to the .tpl files in the main branch or a pull request for mainthat includes changes to the .tpl: https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/.github/workflows/call-run-ss3-with-est.yml#L5-L14.

**Comment by iantaylor-NOAA** [comment]
I'm going to mark my calendar to work on this after getting past a Think Tank on Tuesday next week.
If we don't like the change, thanks to git it will be easy to switch back to the status-quo approach.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA wondering if you want me to take a stab a this given you are getting close to the petrale deadline?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, yes please. You've been working on {[ghactions4r](https://github.com/nmfs-fish-tools/ghactions4r/)} lately so seem more likely to make this change correctly. I think @e-gugliotti-NOAA was on leave when it was first posted, so you two should coordinate.

To recap for those like me who forgot the plan discussed above, the idea is to move the .yml files from the workflows repo into stock-synthesis which will
* reduce the number of files to maintain (currently we have a separate [call-build-ss3.yml](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/.github/workflows/call-build-ss3.yml) in stock-synthesis which calls [build-ss3.yml](https://github.com/nmfs-stock-synthesis/workflows/blob/main/.github/workflows/build-ss3.yml) in workflows.
* make it easier to run the github actions for branches by not requiring both files in the pair to be changed.
* avoid the challenge of figuring out where to post an issue related to the github actions: workflows or stock-synthesis.

There should be zero impact on the workflows themselves in terms of when they run or where to look for error messages when they fail as all that is controlled and explored on the stock-synthesis side already.

**Comment by e-gugliotti-NOAA** [comment]
Thank you Ian, I was out when this was initially discussed. Just sent @kellijohnson-NOAA a google meet invite to plan out doing this so that we aren't both trying to do the same thing separately.
@iantaylor-NOAA would you want to keep r4ss-extra-tests.yml in the workflows repo or would you like to move that to the r4ss repo since it is called from there?
@kellijohnson-NOAA would you want to keep update-ss3-version.yml in the workflows repo or would you like to move that to the ss3sim repo?
Is the goal here to potentially get rid of the workflows repo altogether?

**Comment by iantaylor-NOAA** [comment]
@e-gugliotti-NOAA, yes the goal is to get ride of the workflows repo entirely. 

My memory of the original motivation to have workflows as a separate repository was that it would be easier to have all the workflows in a central location for use by stock-synthesis, r4ss, ss3sim, etc. However, as github actions have evolved, our understanding of them has evolved, and tools like r-lib/actions as well as the ghactions4r package have been developed, the benefit of having a separate repository for workflows doesn't seem worth the extra work involved in keeping things in sync.

I'm happy to move r4ss-extra-tests.yml to r4ss but one thing I've been thinking about is that it might be good to run that whenever there's a change in r4ss OR a change in SS3. That can still happen regardless of where the .yml file is located.

**Comment by e-gugliotti-NOAA** [comment]
Appropriate workflows have been transferred to the stock-synthesis repo in PR #448 - see passing GitHub actions [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions?query=branch%3Atransfer-workflows).

**Comment by kellijohnson-NOAA** [comment]
It would be really helpful if you could fill in the rest of this table @e-gugliotti-NOAA (feel free to just edit this comment or move the table to a different comment, i.e., closer to the top of this issue 🥇) and change the :x: to ✔️ when completed or there is an open PR to complete it. That way we have accountability that all workflows have been transferred, which was one of my first questions when I started to review #448. I am obviously still uncertain where some of the workflows will be moved to.

|workflows|to|complete|
|---|---|---|
build-ss3-manual-html.yml | doc | :x: |
build-ss3-manual-pdf.yml | doc |  :x:|
build-ss3-warnings.yml | stock-synthesis| ✔️ |
build-ss3.yml | stock-synthesis| ✔️ |
check-ss3-models-run.yml | |  :x:|
deploy-ss3-docs.yml | doc |  :x:|
r4ss-extra-tests.yml | |  :x:|
run-ss3-mcmc.yml | stock-synthesis| ✔️ |
run-ss3-no-est.yml | stock-synthesis| ✔️ |
run-ss3-with-est.yml | stock-synthesis| ✔️ |
test-r4ss-with-ss3.yml | stock-synthesis| ✔️ |
update-ss3-version.yml | | :x: |

**Comment by e-gugliotti-NOAA** [comment]
@kellijohnson-NOAA I have moved it up to the top of the issue and filled it in

**Comment by kellijohnson-NOAA** [comment]
I do not like the idea of archiving or leaving the workflows repository because it implies that no better solution was found, I would like to work towards migrating whatever we feel is needed to other repositories and deleting the repository.

**Comment by iantaylor-NOAA** [comment]
Sounds good to me. I will quickly look through any issues that I think we can close. 
Anything we can't close could be transfered to stock-synthesis (or any other appropriate repo) and have a "workflows" tag added to it.

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA and I have close or moved some issues and we're down from 19 to 13 open issues remaining. I need to focus on other stuff for a while, but I think that many of the remaining workflows issues could be converted to a checklist in a single larger issue here at stock-synthesis. For instance, the "improve ss3 workflows" issue https://github.com/nmfs-stock-synthesis/workflows/issues/3 could be expanded to include things like the 4 issues with title "automate...." among others.

@e-gugliotti-NOAA, but perhaps you can take the next look at these things. I don't see a need to move too fast with all this, only to keep momentum rather than have the moving issues out of workflows to remain unfinished for many months.

**Comment by e-gugliotti-NOAA** [comment]
Yes, I'll work on moving all of the workflows over to the appropriate repo and then work through or move those remaining issues in the workflow repo.

**Comment by k-doering-NOAA** [comment]
> I do not like the idea of archiving or leaving the workflows repository because it implies that no better solution was found, I would like to work towards migrating whatever we feel is needed to other repositories and deleting the repository.

One point about archiving vs. deleting, if deleting, the closed issues will go away and all of the commit history, so it is worth thinking about whether that is valuable or not (I think Ian brought this up, but I just wanted to highlight it). A note could be added on the readme about where active issues went.

**Comment by k-doering-NOAA** [comment]
> @k-doering-NOAA should we move update-ss3-version.yml to [ghactions4r](github.com/nmfs-fish-tools/ghactions4r) and keep it as a callable workflow?

I would opt to not, because I think ghactions4r should be only workflows that are widely applicable to R pkgs, whereas this one only applies to pkgs using ss3. But, you can try to convince me it is in scope if you feel strongly about it!

**Comment by kellijohnson-NOAA** [comment]
I still vote for deleting the repository once we have finished moving everything, especially given that @e-gugliotti-NOAA has gone through all of the work of transferring file history for those files that we are keeping.

**Comment by e-gugliotti-NOAA** [comment]
ss3-workflows is now archived
