### ISSUE TITLE
Add additional compile (or update existing) for Mac OS 13?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#480]
@31ingrid (Ingrid Spies at AFSC) is having issues running the current Mac OS release of SS3 on her new Mac with a message "Your system has run out of application memory" even for simple models.
She has macOS Ventura 13.4 while we're using the `macos-latest` for compiling SS3 in github actions, which is apparently version 12. Mac OS 13 is available as well but we have to specify it: https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/2a0368dd54d99065367bce231b0e5610128deacb/.github/workflows/build-ss3.yml#L21.

@e-gugliotti-NOAA can you explore compiling for the newer Mac OS to see if that solves the problem.

**Comment by allanhicks** [comment]
For the SS class at UW this spring, we had a similar issue (I think) with the M2 chips. @jimianelli was able to compile a version that worked on these newer Macs. It may be worth testing on a few different Mac architectures and OSes. Unfortunately, I do not have a Mac so cannot assist any further.

**Comment by Rick-Methot-NOAA** [comment]
This looks like another good reason for me to be glad we are developing a system to run SS3 routinely in cloud

**Comment by iantaylor-NOAA** [comment]
@allanhicks and @jimianelli, please post an issue here next time something like this comes up so we can solve the problem for all users and not just the folks in the class.

**Comment by e-gugliotti-NOAA** [comment]
Hi all,
I ran made a branch that runs the build workflow with [macos-13](https://github.com/nmfs-stock-synthesis/stock-synthesis/tree/macos-13-test) and that action runs [successfully](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/5730625815) building ss3. I've included the zip file ([ss3.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/12233256/ss3.8.zip)) with executables from that build (ss_osx is the macos 13.5 exe). The [macos-13 image](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) is up to OS Version: macOS 13.5 right now. The other mac images available through GitHub actions are macos-11 and macos-12. I suggest that users look at the Readme for the [macos-latest image](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) and see if there are potential version conflicts with the installed packages listed there. 

@31ingrid, @jimianelli, and @allanhicks - If you are still having problems with ss3 on your mac, feel free to let me know either here, via email, or through Gchat if it's urgent. I'm happy to troubleshoot on the fly with you.

**Comment by e-perl-NOAA** [comment]
Closing because the executable should now work with macos-13.
