### ISSUE TITLE
[Refactor]: Rename repos within nmfs-stock-synthesis organization to add "ss3" in front

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#524]
### Issue description

This plan has been discussed in meetings and resulted in four open Pull Requests thanks to @e-gugliotti-NOAA. I've just reviewed those changes and they all look good, but I think it would be helpful to have an issue outside of those PRs in which to discuss the details of the changes before merging them.

### Summary of issue history, discussion, and major aspects of code development

https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/523/ (for this repo)
https://github.com/nmfs-stock-synthesis/doc/pull/200/
https://github.com/nmfs-stock-synthesis/user-examples/pull/26/
https://github.com/nmfs-stock-synthesis/test-models/pull/47/

### Items to do

Here are a few tasks that seems worth planning for. Please edit this list as needed.
- [x] Complete the review of the 4 PRs. Should all three of @Rick-Methot-NOAA, @kellijohnson-NOAA and @iantaylor-NOAA review all 4?
- [x] Merge the changes in all 4 and confirm that the github actions work again
- [ ] Decide what to do with the other 10 repos in nmfs-stock-synthesis

repository | needs repo names updated | updated in branch | branch merged
-- | -- | -- | -- 
ICES-course-2023 | yes | yes |
ssi | no | no |
.github-private | yes | yes |
.github | yes | yes |
workflows | to delete | to delete |
get_labels | ? | ? |
helper | ? | ? |
tpl-format | ? | ? |
ss-flowcharts | ? | ? |
nmfs-stock-synthesis.github.io | no | no | 

- [x] Open issues or make changes in other repos, like r4ss and ss3sim, that link to any of the nmfs-stock-synthesis repos
- [ ] **Help folks find the new location of the User Manual** (this seems like the trickiest one)
  - Links to the old repos will forward automatically, such that https://github.com/nmfs-stock-synthesis/ss-documentation automatically forwards to https://github.com/nmfs-stock-synthesis/doc, and both should automatically forward to https://github.com/nmfs-stock-synthesis/ss3-doc in the future.  
  - However, the github pages will not forward, so https://nmfs-stock-synthesis.github.io/doc/ and any bookmarked links to the User Manual won't work. 
  - We could create a new repo at https://github.com/nmfs-stock-synthesis/doc which has a github.io page which provides the location of the new user manual. However, creating a new version of "doc" would break all forwarding to "ss3-doc" because the new repo takes precedence over the forwarding. I'm not sure if that would be better or worse.
  - Posting the new location to the VLab forums and/or the nmfs-stock-synthesis discussions will help.
  - If the nmfs-stock-synthesis org is going to be under https://github.com/noaa-S-T in the future, we'll have to repeat the process of pointing folks in a new direction, so thinking ahead about that may influence the choice of what to do for this first step.

### Does documentation already exist in the SS3 User Manual?

No, the documentation that should be added to the SS3 User Manual pertaining to this issue is provided below.

### Documentation to add to the SS3 User Manual OR link to existing documentation

It may be worth noting somewhere in the user manual that the repo name changed.

### Are r4ss changes needed?

Yes, this issue requires changes to r4ss (if selecting this, please add iantaylor-NOAA as an Assignee in the panel to the right).

### Are SSI changes needed?

No, this issue doesn't require changes to SSI

**Comment by e-gugliotti-NOAA** [comment]
I think that this would be easiest to do right before/in tandem with the next release (this would make it easier in terms of the release for the documentation and not having to do it twice). It will likely take a couple of days where links aren't all correct but it shouldn't take long to get the most important ones sorted out quickly and the rest in the following days. I propose that we do these things on Monday and Tuesday (Oct. 30th and 31st) when @Rick-Methot-NOAA is done with PICES, and it looks like our calendars are more free to dedicate most of the day to implementation and clean-up.

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA Of the 10 repos:

- 1 is the github.io site, which doesn't need changes [so far, will migrate my new website format repo after this is sorted, my website repo also has a branch with the name changes implemented]
- 2 are the readme files for the org landing pages, I have branches with the repo name changes implemented in these as well
- 1 is the workflows repo, which should be deleted, I just pushed a change to comment out all the workflows to make sure deleting the repo is fine
- 1 is the ices course repo which I can work on a branch changing the names this morning
- 1 is the helper shiny app, it doesn't look like there are any links here that would be altered by changing the repo name to ss3-helper, i do need to double check with @k-doering-NOAA to make sure it won't alter anything with the posit connect deployment
- 4 are Neal's repos (including SSI which from a search didn't have any links to the org in it). I don't know what we want to do with the other 3 of Neal's repos aside from SSI

**Comment by Rick-Methot-NOAA** [comment]
A related issue is the [discussions ](https://github.com/nmfs-stock-synthesis/stock-synthesis/discussions) for which we provide access to the public.  But some items in this location are conversations among team members.  Can we segregate public discussions from team discussions?

**Comment by e-gugliotti-NOAA** [comment]
For the team discussions:

Do these team discussions need to be removed from public access? 
  - if so, then a private repo can work
Do we plan on using team discussions in the future? Most discussions seem to happen in PRs and Issues that are still available for the public to view so it doesn't seem like we would use them going forward. 
  - if no AND the team discussions don't need to be removed from public access, then I think they are okay as is
  - if no BUT the team discussions do need to be removed from public access, then a private repo that is archived might be the move
  - if yes, then a private repo can be created

**Comment by Rick-Methot-NOAA** [comment]
Good questions.  To date, I think the content of the Team discussions has been equivalent to the content in Issues and PR, so I think they can remain.
Followup questions in our G_Spaces.

**Comment by Rick-Methot-NOAA** [comment]
Should the ICES course repo be repurposed to a general repo for training material rather than replicate the material each time we teach a new course?  The content can be "tagged" for each course.

**Comment by e-gugliotti-NOAA** [comment]
I think that this is a great idea!

*Elizabeth F. Gugliotti (she/her)*
---

*Scientific Software Specialist for Stock Synthesis*

ECS Federal contracted to

NOAA/NMFS/National Stock Assessment Program

Mobile: 843-469-1074

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA I have changed the repo name for the ices course to be ss3-trainings. I also updated the README.md to reflect his change. If we build this repo out more, we can always create a github.io site with pages for each training.
