### ISSUE TITLE
[Fix]: Fix workflows to use docker image & fix build-ss3-warnings.yml

### ISSUE THREAD

**Issue by e-perl-NOAA** [nmfs-ost/ss3-source-code#563]
### Issue description

Need to fix the workflow files after Johnoel's branch is merged. @Rick-Methot-NOAA I added this to the change-log so that we know to include in the next release notes that there is now the capability to compile ss3 using docker.

### Summary of issue history, discussion, and major aspects of code development

See PR #552 & PR #561 

### Items to do

- [x] Merge @johnoel's admb branch
- [x] Fix workflows to all use the admb docker image
- [x] Fix the build-ss3-warnings.yml and the ref file for it with it using the docker imager (the fixes are in the `admb-docker-attempt2` branch).
- [x] Change to create a ss3.exe (including tpl names) across all build files (see work @Rick-Methot-NOAA started on the `update-makefile` branch)
- [x] Update any of the contributing material that there is now an option to compile ss3 using docker (if needed)

### Does documentation already exist in the SS3 User Manual?

No, the documentation that should be added to the SS3 User Manual pertaining to this issue is provided below.

### Documentation to add to the SS3 User Manual OR link to existing documentation

NA (all GitHub actions focused).

### Are r4ss changes needed?

No, this issue doesn't require changes to r4ss

### Are SSI changes needed?

No, this issue doesn't require changes to SSI

**Comment by Rick-Methot-NOAA** [comment]
Excellent to see this success.  A final step could be a vignette showing how to work with docker.

**Comment by johnoel** [comment]
Okay, will do.  Please hold off on the merge...

**Comment by johnoel** [comment]
the build-ss3.yml tests building ss3 before installing ADMB.  I will update the manuals to describe the workflow with docker.
