### ISSUE TITLE
revise SPR_SERIES in Report.sso to clarify 

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#607]
The use of multiple columns in the SPR_SERIES with the same column name ("Bio_all" and "Bio_Smry") with "Actual:" in between can be confusing:
https://github.com/nmfs-ost/ss3-source-code/blob/95ed8550ae26208ca4ff2b146a945d028337b2a4/SS_write_report.tpl#L1575-L1576

I think it may be worth appending something to the columns that don't match what's in TIME_SERIES to clarify the difference.

**Comment by Rick-Methot-NOAA** [comment]
Does r4ss read anything from the "actual" columns in this table?
If not, I suggest that the content of the actual columns be reviewed for usefulness and perhaps some items moved into different location, then removing those columns from this table.

**Comment by Rick-Methot-NOAA** [comment]
@iantaylor-NOAA 
Propose to condense table to just the equilibrium quantities
And to add most of "actual" columns to a new table dedicated to reporting annual quantities

**Comment by iantaylor-NOAA** [comment]
@Rick-Methot-NOAA, sorry, forgot to reply to this yesterday.

The r4ss::SS_output() function reads the whole table but by default R changes the 2nd of the duplicate column names to "Bio_all.1"        
and "Bio_Smry.1" so they are unique. I doubt that anyone uses those renamed columns and the values are available in the TIME_SERIES table anyway. The mistake that I saw which alerted me to this involved using the equilibrium value and thinking it was the actual. I think separate tables makes sense unless it would be redundant with TIME_SERIES.

**Comment by Rick-Methot-NOAA** [comment]
Thanks for feedback.  Time_Series is by season and area.  Actual values in SPR table are all annual.  I can work towards giving all output columns unique, informative headers.

**Comment by Rick-Methot-NOAA** [comment]
I will stop reporting aveF and maxF in this table because it's interpretation will be ambiguous in a multi-area model.
The intended reporting of AveF and maxF can now be done with post-processing of other F output tables.
