### ISSUE TITLE
revise RECR_DIST output to work better for models without 50/50 sex ratio at recruitment?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#611]
The 2nd dimension of the `recr_dist` array has length equal to the product of the number of growth patterns and number of sexes:
https://github.com/nmfs-ost/ss3-source-code/blob/69cc71611cf790d520a53f7ee47fe6885fdeb8fe/SS_param.tpl#L157
However the RECRUITMENT_DIST output in Report.sso only loops over growth patterns, not sexes within them:
https://github.com/nmfs-ost/ss3-source-code/blob/69cc71611cf790d520a53f7ee47fe6885fdeb8fe/SS_write_report.tpl#L1031-L1043

This works fine for the huge majority of models that are either 1-sex or have the fraction female fixed at 0.5.

However, @akatan999 shared a model (shared with SS3 developers on Google Drive [here](https://drive.google.com/drive/folders/1Uy8yju7HlLt6m8SrMGwAw_k9k2W-NprB)) with hermaphroditism and multiple areas where the fish recruit to both areas as males but the values in the table only show the tiny fraction of females recruiting to each area:
```
RECRUITMENT_DIST report:10
Settle# settle_timing# G_pattern Area Settle_Month Seas Age Time_w/in_seas Frac/sex
1 1 1 1 1 1 0 0 4.43463e-07
2 1 1 2 1 1 0 0 5.56537e-07
```

Could that table be revised to either sum across females and males OR have separate rows for both females and males?

**Comment by iantaylor-NOAA** [comment]
Update: I just changed the code in https://github.com/r4ss/r4ss/commit/2081ce2df76e12358a50bbbf16c4ab339b5329e8 to rescale the recruitments to sum to 1.0 before plotting. It may still be worth revising the SS3 output but the confusing plot which led to this issue has been resolved:
![image](https://github.com/user-attachments/assets/f81b5091-9125-414c-ba14-f3b02f236c31)

**Comment by Rick-Methot-NOAA** [comment]
The values being plotted are just the frac female.  I will revise the SS3 output table to also output the fraction male.
