### ISSUE TITLE
Anyone still using Mac OS 12? Deprecate the build that's failing?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#629]
The build-ss3 github action is failing because of errors in the macos-12 build. The macos-14 build is working as are windows-latest and ubuntu-latest: https://github.com/nmfs-ost/ss3-source-code/actions/workflows/build-ss3.yml.

Among the warning messages is the following:

> **Warning: You are using macOS 12.**
> We (and Apple) do not provide support for this old version.
> It is expected behaviour that some formulae will fail to build in this old version.
> It is expected behaviour that Homebrew will be buggy and slow.
> Do not create any issues about this on Homebrew's GitHub repositories.
> Do not create any issues even if you think this message is unrelated.
> Any opened issues will be immediately closed without response.
> Do not ask for help from Homebrew or its maintainers on social media.
> You may ask for help in Homebrew's discussions but are unlikely to receive a response.
> Try to figure out the problem yourself and submit a fix as a pull request.
> We will review it but may or may not accept it.

That makes me think we should remove the macos-12 build from the workflow and trust that mac users have all upgraded to newer versions. If anyone is aware of folks still using OS 12, please comment here.

**Comment by iantaylor-NOAA** [comment]
@e-perl-NOAA just noted that this has been resolved in #621 but the "191-spawner-recruitment-with-a-b-formulation" branch associated with PR #442 is behind main and doesn't include that update. Rebasing that branch onto main could resolve the problem, as would just merging it into main.

**Comment by e-perl-NOAA** [comment]
Won't fix as MacOS12 isn't even used for gh-actions anymore.
