### ISSUE TITLE
[Bug]: incorrect header written by Windows exe in new release

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-ost/ss3-source-code#636]
### Describe the bug

When I manually download the ss3_win.exe file form https://github.com/nmfs-ost/ss3-source-code/releases/tag/v3.30.23 or run `r4ss::get_ss3_exe()` and run a model, the resulting files have a header which begins `#V3.30.22.beta: not an official version of SS;_safe;_compile_date:_Oct 31 2024`.

### To Reproduce

Download Windows exe from release page and run any model.

### Expected behavior

This differs from the in-process update of the User Examples files (https://github.com/nmfs-ost/ss3-user-examples/pull/38/) which were created by GitHub action using ubuntu instead of Windows and show the correct header: `#V3.30.23.00;_safe;_compile_date:_Oct 31 2024`.

### Which OS are you seeing the problem on?

Windows

### Which version of SS3 are you seeing the problem on?

3.30.23

### Additional Context

I don't know if this is caused by an issue with compiling the windows version, or just adding the correct file to the release.
Regardless of the solution, my suggestion would be to just replace the exe on the release page and post a message to the forum saying what was done, rather than issue a separate bug-fix release.

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA I'll look into the build to see if it's an issue there.

**Comment by e-perl-NOAA** [comment]
Fixed exe added to release.
