### ISSUE TITLE
log(quantities) for sd_variables

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ss3-source-code#79]
Imported from redmine, Issue [#78894](https://vlab.ncep.noaa.gov/redmine/issues/78894)
 Opened by @RickMethot on 2020-05-22
Status when imported: Under Review
 
per email conversation with Henning Winkler, there is statistical merit in getting the variance of log(SSB/SSBmsy) and log(F/Fmsy).  It would be easy to add this to the existing set of std options.  I'd propose adding 10 to the option such that setting option ==12 rather than ==2 would invoke log(ratio).

Rick

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA I added this to the change log since you noticed that it wasn't previously added with the 3.30.19 release.

**Comment by Rick-Methot-NOAA** [comment]
good.  Any we can mention it in the upcoming release notes
